class Hecsa::Cube
  # Moves are represented as anagrams of the solved state. An x rotation, for
  # example, makes it so that whatever facelet was at location I is now at A.
  MOVES = {
    U:  "DdAaBbCc1IiJfGgHh2MmNjKkLl3QqRnOoPp4EeFrSsTt5UuVvWwXx6",
    L:  "SaBbCcRr1HhEeFfGg2AiJjKkDd3MmNnOoPp4QqXxUsTt5IuVvWwLl6",
    F:  "AaBbFfGd1EeUuVgHh2LlIiJjKk3DmNnOoCc4QqRrSsTt5PpMvWwXx6",
    R:  "AaJjKcDd1EeFfGgHh2IiVvWkLl3PpMmNnOo4CqRrSsBb5UuTtQwXx6",
    B:  "NnObCcDd1BeFfGgAa2IiJjKkLl3MmWwXoPp4TtQqRrSs5UuVvHhEx6",
    D:  "AaBbCcDd1EeFfSsTh2IiJjGgHl3MmNnKkLp4QqRrOoPt5XxUuVvWw6",
    u:  "DdAaBbCc1IiJjGgHl3MmNnKkLp4QqRrOoPt5EeFfSsTh2UuVvWwXx6",
    l:  "SsBbCqRr5HhEeFfGg2AaJjKcDd1MmNnOoPp4QwXxUuTt6IiVvWkLl3",
    f:  "AaBeFfGg2ExUuVvHh6LlIiJjKk3DdNnObCc1QqRrSsTt5PpMmWwXo4",
    r:  "AiJjKkDd3EeFfGgHh2IuVvWwLl6PpMmNnOo4CcRrSaBb1UsTtQqXx5",
    b:  "NnOoCcDm4BbFfGdAa1IiJjKkLl3MvWwXxPp6TtQqRrSs5UuVgHhEe2",
    d:  "AaBbCcDd1EeFrSsTt5IiJfGgHh2MmNjKkLl3QqRnOoPp4XxUuVvWw6",
    E:  "AaBbCcDd1EeFrGgHt5IiJfKkLh2MmNjOoPl3QqRnSsTp4UuVvWwXx6",
    M:  "AsBbCqDd5EeFfGgHh2IaJjKcLl1MmNnOoPp4QwRrSuTt6UiVvWkXx3",
    S:  "AaBeCcDg2ExFfGvHh6IiJjKkLl3MdNnObPp1QqRrSsTt5UuVmWwXo4",
    x:  "IiJjKkLl3FfGgHhEe2UuVvWwXx6PpMmNnOo4CcDdAaBb1SsTtQqRr5",
    y:  "DdAaBbCc1IiJjKkLl3MmNnOoPp4QqRrSsTt5EeFfGgHh2VvWwXxUu6",
    z:  "HhEeFfGg2XxUuVvWw6LlIiJjKk3DdAaBbCc1RrSsTtQq5PpMmNnOo4",
    U2: "CcDdAaBb1MmNfGgHh2QqRjKkLl3EeFnOoPp4IiJrSsTt5UuVvWwXx6",
    L2: "UaBbCcXx1GgHhEeFf2SiJjKkRr3MmNnOoPp4QqLlIsTt5AuVvWwDd6",
    F2: "AaBbUuVd1EePpMgHh2KkLlIiJj3GmNnOoFf4QqRrSsTt5CcDvWwXx6",
    R2: "AaVvWcDd1EeFfGgHh2IiTtQkLl3OoPpMmNn4KqRrSsJj5UuBbCwXx6",
    B2: "WwXbCcDd1OeFfGgNn2IiJjKkLl3MmHhEoPp4SsTtQqRr5UuVvAaBx6",
    D2: "AaBbCcDd1EeFfOoPh2IiJjSsTl3MmNnGgHp4QqRrKkLt5WwXxUuVv6",
    u2: "CcDdAaBb1MmNnGgHp4QqRrKkLt5EeFfOoPh2IiJjSsTl3UuVvWwXx6",
    l2: "UuBbCwXx6GgHhEeFf2SsJjKqRr5MmNnOoPp4QkLlIiTt3AaVvWcDd1",
    f2: "AaBxUuVv6EoPpMmHh4KkLlIiJj3GgNnOeFf2QqRrSsTt5CcDdWwXb1",
    r2: "AuVvWwDd6EeFfGgHh2IsTtQqLl5OoPpMmNn4KkRrSiJj3UaBbCcXx1",
    b2: "WwXxCcDv6OoFfGmNn4IiJjKkLl3MgHhEePp2SsTtQqRr5UuVdAaBb1",
    d2: "AaBbCcDd1EeFnOoPp4IiJrSsTt5MmNfGgHh2QqRjKkLl3WwXxUuVv6",
    E2: "AaBbCcDd1EeFnGgHp4IiJrKkLt5MmNfOoPh2QqRjSsTl3UuVvWwXx6",
    M2: "AuBbCwDd6EeFfGgHh2IsJjKqLl5MmNnOoPp4QkRrSiTt3UaVvWcXx1",
    S2: "AaBxCcDv6EoFfGmHh4IiJjKkLl3MgNnOePp2QqRrSsTt5UuVdWwXb1",
    x2: "UuVvWwXx6GgHhEeFf2SsTtQqRr5OoPpMmNn4KkLlIiJj3AaBbCcDd1",
    y2: "CcDdAaBb1MmNnOoPp4QqRrSsTt5EeFfGgHh2IiJjKkLl3WwXxUuVv6",
    z2: "WwXxUuVv6OoPpMmNn4KkLlIiJj3GgHhEeFf2SsTtQqRr5CcDdAaBb1",
    U_: "BbCcDdAa1QqRfGgHh2EeFjKkLl3IiJnOoPp4MmNrSsTt5UuVvWwXx6",
    L_: "IaBbCcLl1FfGgHhEe2UiJjKkXx3MmNnOoPp4QqDdAsTt5SuVvWwRr6",
    F_: "AaBbPpMd1EeCcDgHh2JjKkLlIi3VmNnOoUu4QqRrSsTt5FfGvWwXx6",
    R_: "AaTtQcDd1EeFfGgHh2IiBbCkLl3NnOoPpMm4WqRrSsVv5UuJjKwXx6",
    B_: "HhEbCcDd1XeFfGgWw2IiJjKkLl3MmAaBoPp4RrSsTtQq5UuVvNnOx6",
    D_: "AaBbCcDd1EeFfKkLh2IiJjOoPl3MmNnSsTp4QqRrGgHt5VvWwXxUu6",
    u_: "BbCcDdAa1QqRrGgHt5EeFfKkLh2IiJjOoPl3MmNnSsTp4UuVvWwXx6",
    l_: "IiBbCkLl3FfGgHhEe2UuJjKwXx6MmNnOoPp4QcDdAaTt1SsVvWqRr5",
    f_: "AaBoPpMm4EbCcDdHh1JjKkLlIi3VvNnOxUu6QqRrSsTt5FfGgWwXe2",
    r_: "AsTtQqDd5EeFfGgHh2IaBbCcLl1NnOoPpMm4WwRrSuVv6UiJjKkXx3",
    b_: "HhEeCcDg2XxFfGvWw6IiJjKkLl3MdAaBbPp1RrSsTtQq5UuVmNnOo4",
    d_: "AaBbCcDd1EeFjKkLl3IiJnOoPp4MmNrSsTt5QqRfGgHh2VvWwXxUu6",
    E_: "AaBbCcDd1EeFjGgHl3IiJnKkLp4MmNrOoPt5QqRfSsTh2UuVvWwXx6",
    M_: "AiBbCkDd3EeFfGgHh2IuJjKwLl6MmNnOoPp4QcRrSaTt1UsVvWqXx5",
    S_: "AaBoCcDm4EbFfGdHh1IiJjKkLl3MvNnOxPp6QqRrSsTt5UuVgWwXe2",
    x_: "SsTtQqRr5HhEeFfGg2AaBbCcDd1NnOoPpMm4WwXxUuVv6IiJjKkLl3",
    y_: "BbCcDdAa1QqRrSsTt5EeFfGgHh2IiJjKkLl3MmNnOoPp4XxUuVvWw6",
    z_: "NnOoPpMm4BbCcDdAa1JjKkLlIi3VvWwXxUu6TtQqRrSs5FfGgHhEe2",
  }

  # moves which affect the orientation of the cube
  ORIENTAL = {
    x: "x", y: "y", z: "z", E: "y'", M: "x'", S: "z",
    u: "y", l: "x'", f: "z", r: "x", b: "z'", d: "y'",
    x2: "x2", y2: "y2", z2: "z2", E2: "y2", M2: "x2", S2: "z2",
    u2: "y2", l2: "x2", f2: "z2", r2: "x2", b2: "z2", d2: "y2",
    x_: "x'", y_: "y'", z_: "z'", E_: "y", M_: "x", S_: "z'",
    u_: "y'", l_: "x", f_: "z'", r_: "x'", b_: "z", d_: "y''",
  }
end
